version: '3'
services:
  db:
    image: mysql:5.7
    container_name: motion-detection-db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    env_file:
      - docker/motion-detection.env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  dev:
    image: node:dubnium
    volumes:
      - .:/home/node/dev
    container_name: motion-detection-dev
    ports:
      - "9229:9229"
      - "3000:3000"
    user: "node"
    working_dir: /home/node/dev
    stdin_open: true
    tty: true
    environment:
      - SHELL=/bin/bash
    env_file:
      - docker/motion-detection.env
    depends_on:
      - "db"
